---
title: "Daniel Skowroński [skowronski.pro - professional homepage]"

baseURL: "https://skowronski.pro/"

languageCode: "en-us"
enableRobotsTXT: true

buildDrafts: true

markup:
  goldmark:
    renderer:
      unsafe: true

theme: blowfish

menu:
  main:
    - identifier: contact
      name: contact
      url: /contact/
      weight: 10
    - identifier: experience
      name: experience
      url: /professional-experience/
      weight: 20
    - identifier: CV
      name: CV
      url: /cv.pdf
      weight: 30
    - identifier: FAQ
      name: FAQ
      url: /faq/
      weight: 40

deployment:
  targets:
    name: s3
    URL: s3://skowronski.pro?region=eu-central-1

author:
  name: "Daniel Skowroński"
  image: "img/memoji.jpg"
  headline: "[skowronski.pro - professional homepage]"
  links:
    - github: "https://github.com/danielskowronski/"
    - linkedin: "https://linkedin.com/in/daniel-skowronski/"
    - blogger: "https://blog.dsinf.net/"
    - blogger: "https://foto.dsinf.net/"
    - keybase: "https://keybase.io/dskowronski"
    - email: "mailto:daniel@skowron.ski"

disableKinds:
  - "taxonomy"
  - "term"

redirects:
  - from: "/cv-partials/"
    to: "/404.html"
    status: 404

params:
  colorScheme: "blue"
  defaultAppearance: "dark"

  logo: "img/logo.png"

  enableSearch: false

  homepage:
    layout: "profile"

  article:
    showEdit: false
    showDate: false
    showAuthor: false
    showPagination: false
    showReadingTime: false
    showWordCount: false
    sharingLinks: false

  taxonomy:
    showTermCount: false

